import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Inter} from "next/font/google";
import Link from "next/link";
import Image from "next/image";

const inter = Inter({subsets:["latin"]});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body className={`${inter.className} bg-gray-50 flex flex-col min-h-screen text-gray-900`}>

        <nav className="bg-white border-b border-gray-200 sticky top-0 z-10">
          <div className="max-w-5xl mx-auto px-6 py-4 flex justify-between items-center">
            <Link href="/" className="flex items-center gap-3 hover:opacity-80 transition group">
              <div className="relative w-10 h-10">
                <Image
                  src="/logo.png"
                  alt="Logo Divkom HME ITB"
                  fill
                  className="object-contain"
                  sizes="40px"
                />
              </div>
             <span className="text-gray-800 font-extrabold">Blog Divkom HME ITB</span>
            </Link>
            <div className="text-sm font-extrabold text-gray-500 hover:text-orange-600 transition">
              <Link href="/">Home</Link>
            </div>
          </div>
        </nav>

        <main className="flex-grow">
          {children}
        </main>

        <footer className="bg-whie border-t border-gray-200 mt-12 py-8 text-center text-gray-500 text-sm">
          <p>Apakah kita akan merevisi ini seperti modul Arsikom??</p>
        </footer>

      </body>
    </html>
  );
}
